spawn_players: true

drone:
  position: [-4.0, 0.0, 2.0]

ball:
  position: [0.0, 0.0, 0.11]

kicks:
  - name: kick1
    position: [-2.0, -2.0, 0.0]
  - name: kick2
    position: [5.0, 5.0, 0.0]
  - name: kick3
    position: [-5.0, 5.0, 0.0]

players:
  - name: player1
    position: [-2.0, -2.0, 0.0]
  - name: player2
    position: [5.0, 5.0, 0.0]
  - name: player3
    position: [-5.0, 5.0, 0.0]